### ISSUE TITLE
下载资料

### ISSUE THREAD

**Issue by franklinsu** [hansxiao7/ML2020#1]
大佬，能不能把你的这个仓库拷到gitee中，我在国内想下载你的仓库中的数据集下载不了呢

**Comment by hansxiao7** [comment]
试试用http://kinolien.github.io/gitzip/
不行的话可以直接留个微信号我传给你

**Comment by franklinsu** [comment]
谢谢你的回复，你给的网址可以正常下载了。谢谢你，加油呀
